hydra:
  run:
    dir: '/root/hydra/${task_name}/${now:%Y-%m-%d_%H-%M-%S}'

task_name: 'esm2_t33_650M_UR50D_ProtST'

# path
data_path: '/root/data/datasets/ProtSTData'
output_path: '/root/data/FST/${task_name}/local_650'

# model
protein_model_name: '/root/data/backbones/esm2_t33_650M_UR50D'
protein_model_fixed: False
text_model_name: '/root/data/backbones/BiomedNLP-PubMedBERT-base-uncased-abstract'
text_model_fixed: True
projection_dim: 512
fusion_num_heads: 8
fusion_num_layers: 1
fusion_batch_norm: True
mlp_num_layers: 2
mlm_probability: 0.15

protein_mask_range: 10
proto_dim: 512
proto_num: 512
local_pool: 'avg'
fragment_range: 100


# dataset
dataset: 'ProtDescribe'
max_length: 1024

text_attributes: ['PROTEIN NAME', 'FUNCTION', 'SUBCELLULAR LOCATION', 'SIMILARITY']
noise_lambda: 3

# train
lr: 0.00001
lr_ratio: 0.1
fp16: True
batch_size: 4
num_epochs: 35
weight_decay: 0.0
warmup_ratio: 0.03

# eval
metric_for_best_model: 'loss'

# task
task: 'FSTPretrainTask'

# loss ablation
mmp: 0
t2p_mlm: 0
local_contrast: 1

# RANK
local_rank: 0