compute_environment: LOCAL_MACHINE
deepspeed_config: 
 deepspeed_config_file: /data3/zhouhanjing/FST/zero2.json
 deepspeed_multinode_launcher: standard
distributed_type: DEEPSPEED
machine_rank: 
main_process_ip: 
main_process_port: 
main_training_function: main
num_machines: 1
num_processes: 2
use_cpu: false
